name: Middleman

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: "4"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
          bundler-cache: true
      - name: Verify i18n
        shell: bash
        run: bundle exec i18n-tasks health
      - name: Build
        shell: bash
        run: |
          bundle exec middleman build
          echo "Missing translations in file(s):"
          ! grep -lr 'translation missing' ./build
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
