name: Middleman

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: "4"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
          bundler-cache: true
      - name: Build
        shell: bash
        run: |
          bundle exec middleman build
          grep -lr 'translation missing' ./build > missing
          if [  -s missing ]; then
             echo "Missing translations in file(s)"
             cat missing
          fi

  deploy:
    name: "Deploy"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    env:
      BUNDLE_JOBS: "4"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
          bundler-cache: true
      - name: Build & Deploy to GitHub Pages
        with:
          REMOTE_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: Kraiany/middleman-gh-pages-action@master
