name: Middleman

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: "4"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Verify i18n
        shell: bash
        run: bundle exec i18n-tasks health
      - name: Build
        shell: bash
        run: |
          bundle exec middleman build --verbose
          echo "Missing translations in file(s):"
          ! grep -lr 'translation missing' ./build
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      - name: Deploy to AWS S3
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: reggionick/s3-deploy@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          private: false
          filesToInclude: ".*/*,*/*,**"
  dependabot:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto-merge Dependabot PRs
        if: ${{(steps.metadata.outputs.update-type == 'version-update:semver-minor') || (steps.metadata.outputs.update-type == 'version-update:semver-patch')}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
