name: Middleman

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Cache Gems
        id: gem-cache
        uses: actions/cache@v1.1.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
      - name: Bundle Install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build
        shell: bash
        run: |
          bundle exec middleman build
          ! grep -r 'translation missing' ./build

  deploy:
    name: "Deploy"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Build & Deploy to GitHub Pages
        with:
          REMOTE_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: yurikoval/middleman-gh-pages-action@master
